export const SET_DRIVER = 'SET_DRIVER'
export const SET_STANDINGS = 'SET_STANDINGS'
export const SET_RACES_RESULTS = 'SET_RACES_RESULTS'
export const SET_QUALIFYINGS_RESULTS = 'SET_QUALIFYINGS_RESULTS'
