export const CARD_SIZE_SMALL = 'small'
export const CARD_SIZE_MEDIUM = 'medium'
export const CARD_SIZE_LARGE = 'large'

export const CARD_COLOR_PRIMARY = 'primary'
export const CARD_COLOR_SECONDARY = 'secondary'
export const CARD_COLOR_HIGHLIGHT = 'highlight'
export const CARD_COLOR_ORANGE = 'orange'
export const CARD_COLOR_YELLOW = 'yellow'
export const CARD_COLOR_GREEN = 'green'
export const CARD_COLOR_RED = 'red'
