export const TOASTER_CLASS = 'toaster'
export const TOAST_CLASS = 'toast'
export const TOAST_CLASS_SUCCESS = 'success'
export const TOAST_CLASS_ERROR = 'error'
export const TOAST_CLASS_WARNING = 'warning'
